/*.$file${../src::QHSM_Test.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: qhsmtst.qm
* File:  ${../src::QHSM_Test.cpp}
*
* This code has been generated by QM 5.1.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${../src::QHSM_Test.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$declare${HSMs::QHsmTst::SM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
static QState QHsmTst_initial(QHsmTst * const me);
static QState QHsmTst_s(QHsmTst * const me);
static QState QHsmTst_s1(QHsmTst * const me);
static QState QHsmTst_s11(QHsmTst * const me);
static QState QHsmTst_s2(QHsmTst * const me);
static QState QHsmTst_s21(QHsmTst * const me);
static QState QHsmTst_s211(QHsmTst * const me);
/*.$enddecl${HSMs::QHsmTst::SM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
