/*.$file${HSMs::../src::ClockAlarm_SM.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: ClockAlarm.qm
* File:  ${HSMs::../src::ClockAlarm_SM.h}
*
* This code has been generated by QM 5.1.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${HSMs::../src::ClockAlarm_SM.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef CLOCK_ALARM_H
#define CLOCK_ALARM_H

enum ClockAlarm_Signals
{
  SET_SIG = Q_USER_SIG,    /* Q_USER_SIG marks the beginning of User Signals */
  OK_SIG,
  ABRT_SIG,
  ALARM_SIG,
  TICK_SIG,
  MAX_SIG
};

enum time_mode
{
  TIME_MODE_24H = 0,
  TIME_MODE_12H,
};

enum alarm_status
{
  ALARM_OFF = 0,
  ALARM_ON
};

typedef enum time_format
{
  FORMAT_24H = 0,
  FORMAT_AM,
  FORMAT_PM,
} time_format_t;

#define INITIAL_CURRENT_TIME    (((10ul*3600ul) + (10ul*60ul) + 10ul) * 10ul)    /* 10 hours 10 minutes 10 seconds */
#define INITIAL_ALARM_TIME      (8ul*3600ul)                                     /* 8 hours */
#define MAX_TIME                (864000ul)                                       /* 24*3600*10 */
/* Display Related Macros */
#define TICKING_CURR_TIME_ROW   (0u)
#define TICKING_CURR_TIME_COL   (3u)

/*.$declare${HSMs::Clock_Alarm_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${HSMs::Clock_Alarm_ctor} ...............................................*/
void Clock_Alarm_ctor(void);
/*.$enddecl${HSMs::Clock_Alarm_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$declare${HSMs::super_ClockAlarm} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
extern QHsm *const super_ClockAlarm;
/*.$enddecl${HSMs::super_ClockAlarm} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif